### ISSUE TITLE
setup a connection to mysql

### ISSUE THREAD

**Issue by m-henderson** [RTask/RTask#31]
we need to give the Django framework a way to connect to mysql. This is as simple as updating the settings. You can see more info here: https://docs.djangoproject.com/en/3.1/ref/databases/

let me know if you have any question or issues.

**Comment by nguyendhse** [comment]
Let me try to work on this task by setup the database config via environment variables

**Comment by m-henderson** [comment]
@nguyendhse not a problem. let me know if you have questions.

**Comment by SoumyaRanjanNaik** [comment]
I can help with MySQL connection. Just let me know if I can give you the config for localhost or for environment variables ?

**Comment by SoumyaRanjanNaik** [comment]
@m-henderson I think you can close this issue now.
