### ISSUE TITLE
When No Tickets in List Show Friendly Message

### ISSUE THREAD

**Issue by m-henderson** [RTask/RTask#7]
Right now, there is just a blank table if the user goes to the ticket list and there are no tickets in the database. 

example: 
![image](https://user-images.githubusercontent.com/16070192/68477070-14267700-01f2-11ea-8cd9-6264db4d2f26.png)

**Comment by Phaqui** [comment]
simple PR ready:

https://github.com/RTask/RTask/pull/10

**Comment by m-henderson** [comment]
@Phaqui  thanks (👍
